// TODO: Configure Firebase for this project.
// Steps:
//   1. Go to https://console.firebase.google.com and create a project
//   2. Add a Web app (and Android/iOS if needed) to the project
//   3. Run `flutterfire configure` in this directory OR manually fill the values below
//
// Run: dart pub global activate flutterfire_cli
//      flutterfire configure
//
// This file will be auto-generated by flutterfire_cli. Placeholder shown below:

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── TODO: Replace with real values from Firebase Console ─────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKMCg6ldMJ4LsaqpJtEG-ZGcMI5T7ygTE',
    appId: '1:196012001824:web:e536a14ad435506c168a45',
    messagingSenderId: '196012001824',
    projectId: 'klventerprises',
    authDomain: 'klventerprises.firebaseapp.com',
    storageBucket: 'klventerprises.firebasestorage.app',
    measurementId: "G-DKS7DBK0YK",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKMCg6ldMJ4LsaqpJtEG-ZGcMI5T7ygTE',
    appId:
        '1:196012001824:android:876543210987654321', // Placeholder if not provided, usually appID varies by platform
    messagingSenderId: '196012001824',
    projectId: 'klventerprises',
    storageBucket: 'klventerprises.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKMCg6ldMJ4LsaqpJtEG-ZGcMI5T7ygTE',
    appId:
        '1:196012001824:ios:876543210987654321', // Placeholder if not provided
    messagingSenderId: '196012001824',
    projectId: 'klventerprises',
    storageBucket: 'klventerprises.firebasestorage.app',
    iosBundleId: 'com.fancyshop.fancyShopAdmin',
  );
}
